/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ValentineImport } from './routes/valentine'
import { Route as UsImport } from './routes/us'
import { Route as MenuImport } from './routes/menu'
import { Route as CancunImport } from './routes/cancun'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ValentineRoute = ValentineImport.update({
  path: '/valentine',
  getParentRoute: () => rootRoute,
} as any)

const UsRoute = UsImport.update({
  path: '/us',
  getParentRoute: () => rootRoute,
} as any)

const MenuRoute = MenuImport.update({
  path: '/menu',
  getParentRoute: () => rootRoute,
} as any)

const CancunRoute = CancunImport.update({
  path: '/cancun',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cancun': {
      preLoaderRoute: typeof CancunImport
      parentRoute: typeof rootRoute
    }
    '/menu': {
      preLoaderRoute: typeof MenuImport
      parentRoute: typeof rootRoute
    }
    '/us': {
      preLoaderRoute: typeof UsImport
      parentRoute: typeof rootRoute
    }
    '/valentine': {
      preLoaderRoute: typeof ValentineImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CancunRoute,
  MenuRoute,
  UsRoute,
  ValentineRoute,
])

/* prettier-ignore-end */
